### ISSUE TITLE
Diverses

### ISSUE THREAD

**Issue by gianperrone** [ProPra16/programmierpraktikum-abschlussprojekt-wegotbroadsinatlanta-1#1]
Ich zitiere mal aus der Aufgabenstellung:
Wenn man den ersten Test für eine Methode schreibt, existiert die Methode noch nicht. Folglich kann der Test nicht kompiliert werden

Teilweise heißen die Testklassen nicht so wie die kompilierten Klassen, wodurch der Compiler Fehler wirft, teilweise kann ich wild durch die Modi wechseln, dann wieder garnicht. (Ja, ich habe Desiigner ausgecheckt). Da müsst ihr noch nachbessern und testen, das Programm erfüllt die Aufgabenstellung nicht.

**Comment by FelixKerlin** [comment]
Hallo Gian,

ich habe folgende Änderungen am Desiigner-Branch vorgenommen:

Zurücksetzen:
- Es gibt jetzt einen Button, der den Code seit dem letzten Phasenwechsel zurücksetzt.
- Bei der Phase Grün springt er außerdem zurück in den Testmodus

Babysteps:
- Babystep-Konfiguration wird nun aus dem Katalog geladen (Nur Römische Zahlen hat dies momentan aktiviert)
- Timer hinzugefügt, der bei jedem Phasenwechsel resettet
- Erreicht der Timer 0 wird die aktuelle Phase zurückgesetzt
- Babysteps sind im Refactor-Modus nicht aktiv

Timetracking:
- Timetracking-Konfiguration wird nun aus dem Katalog geladen
- Zählt im Hintergrund die Zeit, die in jeder Phase verbracht wird und summiert diese auf
- Der Graph über den Knopf oben Rechts kann nun jederzeit angezeigt werden und zeigt die aktuellen Daten

Play/Switch Button:
- Beim Klick auf den Playbutton wird nun immer Test und Code kompiliert und getestet.
- Der Switchbutton wird nach jedem Phasenwechsel deaktivert
- Beim Klick auf den Playbutton werden die Kritieren überprüft, ob der Switchbutton wieder aktiviert wird (Bei Rot: 1 falscher Test oder kompiliert nicht, bei grün und schwarz: 0 falsche Tests und alles kompiliert)

Bugfixes:
- Mehrere kleine Anzeigenfehler und falsche Variablen geändert

Könntest du dir das Programm nochmals angucken und sagen, was noch verbessert werden müsste? 

LG
Felix Kerlin

**Comment by gianperrone** [comment]
Läuft hinreichend gut.
